### ISSUE TITLE
Does modify an object in SBH change the URI?

### ISSUE THREAD

**Issue by Gonza10V** [saisam17/Experimental-Data-Converter#8]
If I change an ovject in SBH does that change de URI?
If the URI changes, how can we tell Flapjack to update that.

**Comment by JMante1** [comment]
Only if you make the object public will the uri change. There is no way this change can be updated via the converter. The two options are to create a standalone plugin which runs as part of publication (not something we support at the moment) or to provide permalinks that don't change. I think the latter is easier and would solve several wider issues so I have requested the feature on sbh. If it is implemented we can update the linkage in the converter.
