### ISSUE TITLE
How to maintain a conection once established through the EDC

### ISSUE THREAD

**Issue by Gonza10V** [saisam17/Experimental-Data-Converter#9]
In the proces of establishing a connection between SBH and Flapjack, Flapjack provides an URL and a modification on the object does not modify its URL. On the other hand a modification in SBH could modify its URI and this sets a new challenge to maintain that connection. How can we update the Flapjack object with the new URI, is it necesary? What would be the best implementation for this, so users made updates or fix errors? Is necesary to track those changes?

**Comment by JMante1** [comment]
I have logged this as an issue for synbiohub. I have asked that a permalink be created that can be used rather than the uri in future. This is not an xdc issue but a synbiohub one (other programmes have this problem too).
